name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install yarn
        run: npm install -g yarn
      - name: Setup test env
        run: |
          touch .env
          echo REPORT_GAS=${{ secrets.REPORT_GAS }} >> .env
          echo ENV=${{ secrets.ENV }} >> .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
          echo OWNER={{ secrets.OWNER }} >> .env
          cat .env
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: npm run test
